# Site settings
title: Co-Labo
email: andres.colubri@umassmed.edu
url: https://co-labo.org/
description: "The Colubri Lab at the Program in Bioinformatics and Integrative Biology at the University of Massachusetts Medical School is a \"collaboratory\""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Co-Labo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/colabobio
  - title: github
    url: https://github.com/codeanticode

# Build settings
markdown: kramdown
permalink: pretty
